const express = require('express');
const cors = require('cors');
require('dotenv').config();

const { PrismaClient } = require('./generated/prisma'); // auto-generated by Prisma
const prisma = new PrismaClient();

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(cors());
app.use(express.json());

// Example API route
app.get('/', (req, res) => {
  res.send('Whiteboard backend is running!');
});

// Start server
app.listen(PORT, () => {
  console.log(`Server is running on http://localhost:${PORT}`);
});
